@startuml auth_flow

user --> auth: add user
auth --> user: form for date
user --> auth: form with date
auth --> eventBus: event "user"
eventBus --> taskTracker: processing "user"
eventBus --> accounting: processing "user"
eventBus --> analytic: processing "user"
auth --> user: OK

user --> auth: login
auth --> user: form for login/password
user --> auth: form with login/password
auth --> user: JWT token

@enduml