@startuml domains

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Boundary(user, "пользователь") {
}

Boundary(task, "управление задачами") {
}

Boundary(accounting, "аккаунтинг") {
}

Boundary(analytic, "аналитика") {
}

Rel(user, task, "")
Rel(user, accounting, "")
Rel(user, analytic, "")

Rel(accounting, analytic, "")

@enduml