@startuml add_user

title событие добавления нового пользователя

object add_user {
login = mail
first_name
last_name
role
}

@enduml

@startuml task_assigned

title событие назначения задачи

object task_assigned {
task_id
login
}

@enduml

@startuml task_completed

title событие выполнения задачи
object task_completed {
task_id
login
}

@enduml

@startuml task_with_cost

title событие с оплатой
object task_completed {
task_id
login
cost
}

@enduml

@startuml manager_report

title событие с заработке менеджера

object manager_report {
login
cost
}

@enduml


@startuml mail

title событие сообщения для пользователя

object mail {
mail_address
body
}

@enduml