@startuml services

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "user")

Boundary(backend, "Backend") {
!startsub taskTracker
System(taskTracker, "task-tracker")
database taskTrackerDB
!endsub
!startsub auth
System(auth, "auth")
database authDB
!endsub
!startsub accounting
System(accounting, "accounting")
database accountingDB
!endsub
!startsub analytic
System(analytic, "analytic")
database analyticDB
!endsub
!startsub eventBus
System(eventBus, "eventBus")
!endsub
!startsub sender
System(sender, "sender")
!endsub
}

Boundary(frontend, "Frontend") {
!startsub Admin
System(admin, "admin")
!endsub
}

Rel(auth, authDB, "")

Rel(taskTracker, eventBus, "")
Rel(taskTracker, taskTrackerDB, "")

Rel(analytic, eventBus, "")
Rel(analytic, analyticDB, "")

Rel(accounting, eventBus, "")
Rel(accounting, accountingDB, "")

Rel(sender, eventBus, "")

Rel(user, admin, "")

Rel(admin, auth, "")
Rel(admin, taskTracker, "")
Rel(admin, accounting, "")
Rel(admin, analytic, "")

Rel(sender, user, "mail")

@enduml