@startuml new_task_flow

title создание новой задачи

!startsub addTask
user --> taskTracker: POST add task
taskTracker --> taskTrackerDB: check user in JWT
taskTracker --> taskTrackerDB: create task for user
taskTracker --> taskTrackerDB: assign task
taskTracker --> eventBus: produce "task assigned"
eventBus --> accounting: consume "task assigned"
accounting --> eventBus: produce "task with cost"
eventBus --> analytic: consume "task with cost"
taskTracker --> user: task_id
!endsub

@enduml
@startuml assign_task_flow

title распределение незавершенных задач

!startsub assignTask
user --> taskTracker: POST assign tasks
taskTracker --> taskTrackerDB: check user in JWT
taskTracker --> taskTrackerDB: assign tasks
taskTracker --> eventBus: produce "task assigned"
eventBus --> accounting: consume "task assigned"
accounting --> eventBus: produce "task with cost"
eventBus --> analytic: consume "task with cost"
!endsub

@enduml
@startuml complete_task_flow

title совершение задачи

!startsub completeTask
user --> taskTracker: POST complete task_id
taskTracker --> taskTrackerDB: check user in JWT
taskTracker --> taskTrackerDB: complete task
taskTracker --> eventBus: produce "task completed"
eventBus --> accounting: consume "task completed"
accounting --> eventBus: produce "task with cost"
eventBus --> analytic: consume "task with cost"
!endsub

@enduml